apiVersion: v1
kind: Pod
metadata: 
    name: tomcat
    labels: 
      app: tomcat
spec:
  containers:
      - name: tomcat
        image: docker635067/test:preethu
        ports:
          - containerPort: 8080
