apiVersion: v1
kind: Pod
metadata: 
    name: nodeapp
    labels: 
      app: nodeapp
spec:
  containers:
      - name: nodeapp
        image: docker635067/test:preethu
        ports:
          - containerPort: 8080
